# Generated by Django 4.2.6 on 2023-10-31 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTypes',
            fields=[
                ('type', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('seq', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'asset_types',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, related_name='asset_type', to='crypto.assettypes')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='CommonAssetDetail',
            fields=[
                ('identifier', models.ForeignKey(db_column='identifier', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asset_detail_identifier', serialize=False, to='crypto.assets')),
                ('symbol', models.CharField(max_length=50)),
                ('coingecko', models.CharField(max_length=255)),
                ('cryptocompare', models.CharField(max_length=255)),
                ('started', models.IntegerField()),
                ('forked', models.ForeignKey(blank=True, db_column='forked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_detail_forled', to='crypto.assets')),
                ('swapped_for', models.ForeignKey(blank=True, db_column='swapped_for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_detail_swapped_for', to='crypto.assets')),
            ],
            options={
                'db_table': 'common_asset_details',
            },
        ),
    ]
