# Generated by Django 4.2.6 on 2023-10-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_evmtoken_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistorySourceType',
            fields=[
                ('type', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('seq', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'price_history_source_types',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('price', models.TextField()),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history_from_identifier', to='crypto.asset')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history_source_types', to='crypto.pricehistorysourcetype')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history_to_identifier', to='crypto.asset')),
            ],
            options={
                'db_table': 'price_history',
            },
        ),
    ]
