# Generated by Django 4.2.6 on 2023-11-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_pricehistorysourcetype_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCache',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('last_queried_ts', models.IntegerField()),
            ],
            options={
                'db_table': 'general_cache',
            },
        ),
        migrations.CreateModel(
            name='UniqueCache',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('last_queried_ts', models.IntegerField()),
            ],
            options={
                'db_table': 'unique_cache',
            },
        ),
    ]
